name: develop
on: 
    pull_request:
        branches:
            - master
            - develop
    push:
        branches:
            - develop
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout develop branch
          - uses: actions/checkout@v2
            with: 
              ref: develop
          - name: Build the TeX files
            uses: ./.github/actions/latex
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITHUB_WORKFLOW: $GITHUB_WORKFLOW