name: release
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Build the TeX files and release the PDF files
            uses: actions/latex
            with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                RELEASE: true